'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        /**
         * Add seed commands here.
         *user
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   name: hashPassword,
         *   isBetaMember: false
         * }], {});
         */

        // tên user là tên của database
        await queryInterface.bulkInsert(
            'product',
            [
                {
                    tenSp: 'Kệ ti vi',
                    chatLieu: 1,
                    giaNhap: '9000000',
                    giaBan: '15000000',
                    giamGia: '20',
                    image: 'avt2.jpg',
                    kichThuoc: 'D180-R60',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Ghế ba thành',
                    chatLieu: 2,
                    giaNhap: '20000000',
                    giaBan: '27000000',
                    giamGia: '',
                    image: 'avt9.jpg',
                    kichThuoc: 'D200-R80',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Sofa da mã NTX1824',
                    chatLieu: 3,
                    giaNhap: '15000000',
                    giaBan: '26250000',
                    giamGia: '17',
                    image: 'sofa-1.jpg',
                    kichThuoc: 'D200-R100',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Sofa Da MLEH-740L',
                    chatLieu: 3,
                    giaNhap: '60000000',
                    giaBan: '89250000',
                    giamGia: '29',
                    image: 'sofa-2.jpg',
                    kichThuoc: 'D200-R100',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bộ Sofa Da Nỉ 9230',
                    chatLieu: 3,
                    giaNhap: '30000000',
                    giaBan: '42000000',
                    giamGia: '23',
                    image: 'sofa-3.jpg',
                    kichThuoc: 'D200-R100',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Sofa Giường 215 – 10',
                    chatLieu: 3,
                    giaNhap: '50000000',
                    giaBan: '73500000',
                    giamGia: '28',
                    image: 'sofa-4.jpg',
                    kichThuoc: 'D200-R100',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Sofa bộ Hugo 8979',
                    chatLieu: 3,
                    giaNhap: '50000000',
                    giaBan: '77000000',
                    giamGia: '30',
                    image: 'sofa-5.jpg',
                    kichThuoc: 'D200-R100',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 1,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },

                {
                    tenSp: 'Bàn ghế ăn mã XBA186',
                    chatLieu: 4,
                    giaNhap: '10000000',
                    giaBan: '22000000',
                    giamGia: '30',
                    image: 'ban-ghe-an-1.jpg',
                    kichThuoc: 'D180-R80-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 2,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn ghế ăn mã XBA185',
                    chatLieu: 4,
                    giaNhap: '8000000',
                    giaBan: '11000000',
                    giamGia: '25',
                    image: 'ban-ghe-an-2.jpg',
                    kichThuoc: 'D160-R80-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 2,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn ghế ăn mã XBA188',
                    chatLieu: 4,
                    giaNhap: '30000000',
                    giaBan: '44000000',
                    giamGia: '25',
                    image: 'ban-ghe-an-3.jpg',
                    kichThuoc: 'D200-R100-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 2,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },

                {
                    tenSp: 'Bàn làm việc hòa phát HP120HL3CPO',
                    chatLieu: 4,
                    giaNhap: '5000000',
                    giaBan: '7150000',
                    giamGia: '8',
                    image: 'ban-lam-viec-1.jpg',
                    kichThuoc: 'D180-R60-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 3,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn làm việc',
                    chatLieu: 2,
                    giaNhap: '10000000',
                    giaBan: '15000000',
                    giamGia: '10',
                    image: 'avt7.jpg',
                    kichThuoc: 'D180-R80-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 3,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn làm việc B2',
                    chatLieu: 4,
                    giaNhap: '5000000',
                    giaBan: '7150000',
                    giamGia: '8',
                    image: 'ban-lam-viec-3.jpg',
                    kichThuoc: 'D120-R60-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 3,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn làm việc B3',
                    chatLieu: 4,
                    giaNhap: '35000000',
                    giaBan: '50000000',
                    giamGia: '10',
                    image: 'ban-lam-viec-4.jpg',
                    kichThuoc: 'D180-R80-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 3,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn làm việc B4',
                    chatLieu: 4,
                    giaNhap: '35000000',
                    giaBan: '50000000',
                    giamGia: '10',
                    image: 'ban-lam-viec-5.jpg',
                    kichThuoc: 'D160-R80-C65',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 3,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },

                {
                    tenSp: 'Bàn trang điểm',
                    chatLieu: 2,
                    giaNhap: '8000000',
                    giaBan: '12000000',
                    giamGia: '',
                    image: 'avt4.1.jpg',
                    kichThuoc: 'D120-R60-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Bàn trang điểm PU',
                    chatLieu: 2,
                    giaNhap: '8000000',
                    giaBan: '16000000',
                    giamGia: '',
                    image: 'avt4.jpg',
                    kichThuoc: 'D120-R60-C75',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Giường hoàng gia',
                    chatLieu: 1,
                    giaNhap: '17000000',
                    giaBan: '27000000',
                    giamGia: '',
                    image: 'avt6.jpg',
                    kichThuoc: 'D220-R180',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Giường PU',
                    chatLieu: 1,
                    giaNhap: '15000000',
                    giaBan: '20000000',
                    giamGia: '',
                    image: 'avt10.jpg',
                    kichThuoc: 'D220-R180',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Giường chữ X',
                    chatLieu: 1,
                    giaNhap: '15000000',
                    giaBan: '20000000',
                    giamGia: '',
                    image: 'avt11.jpg',
                    kichThuoc: 'D220-R180',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Tủ áo 3 buồng',
                    chatLieu: 5,
                    giaNhap: '22000000',
                    giaBan: '28000000',
                    giamGia: '',
                    image: 'tu-ao-1.jpg',
                    kichThuoc: 'D197-R64-C220',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    tenSp: 'Tủ áo 4 buồng PU',
                    chatLieu: 1,
                    giaNhap: '25000000',
                    giaBan: '34000000',
                    giamGia: '',
                    image: 'tu-ao-pu-1.jpg',
                    kichThuoc: 'D197-R64-C220',
                    soLuotDanhGia: 0,
                    tongDanhGia: 0,
                    producttypeId: 4,
                    soLuong: 50,
                    trangThai: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
            ],
            {},
        );
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    },
};
